## Installing RAPIDS

In [ ]:
!git clone https://github.com/rapidsai/rapidsai-csp-utils.git
!bash rapidsai-csp-utils/colab/rapids-colab.sh stable

Cloning into 'rapidsai-csp-utils'...
remote: Enumerating objects: 390, done.
remote: Counting objects: 100% (121/121), done.
remote: Compressing objects: 100% (70/70), done.
remote: Total 390 (delta 89), reused 51 (delta 51), pack-reused 269
Receiving objects: 100% (390/390), 107.11 KiB | 5.64 MiB/s, done.
Resolving deltas: 100% (191/191), done.
PLEASE READ FOR 21.06
********************************************************************************************************
Another release, another script change.  We had to revise the script, which now:
1. Does a more comprehensive install
2. Includes BlazingSQL
3. is far easier for everyone to understand and maintain

The script will require you to add these 5 cells to your notebook.  We have also created a new startup template: 
https://colab.research.google.com/drive/1TAAi_szMfWqRfHVfjGSqnGVLr_ztzUM9?usp=sharing

CHANGES T
CELL 1:
    # This get the RAPIDS-Colab install files and test check your GPU.  Run cells 1 and 2 only.
    # Pleas

In [ ]:
!python --version

Python 3.10.11


In [ ]:
!python rapidsai-csp-utils/colab/env-check.py

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.1/53.1 kB 6.1 MB/s eta 0:00:00
***********************************************************************
Woo! Your instance has the right kind of GPU, a NVIDIA A100-SXM4-40GB!
We will now install RAPIDS via pip!  Please stand by, should be quick...
***********************************************************************



In [ ]:
!bash rapidsai-csp-utils/colab/update_gcc.sh
import os
os._exit(00)

Updating your Colab environment.  This will restart your kernel.  Don't Panic!
Found existing installation: cupy-cuda11x 11.0.0
Uninstalling cupy-cuda11x-11.0.0:
  Successfully uninstalled cupy-cuda11x-11.0.0
Get:1 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu focal InRelease [18.1 kB]
Get:2 https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/ InRelease [3,622 B]
Hit:3 http://ppa.launchpad.net/cran/libgit2/ubuntu focal InRelease
Hit:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease
Hit:5 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal InRelease
Get:6 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu focal InRelease [24.3 kB]
Get:7 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu focal InRelease [17.5 kB]
Hit:8 http://archive.ubuntu.com/ubuntu focal InRelease
Get:9 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Hit:10 http://ppa.launchpad.net/ubuntugis/ppa/ubuntu focal InRelease
Get:11 http://ppa.laun

In [ ]:
## Installing CondaColab.  This will restart your kernel again
import condacolab
condacolab.install()

⏬ Downloading https://github.com/conda-forge/miniforge/releases/download/23.1.0-1/Mambaforge-23.1.0-1-Linux-x86_64.sh...
📦 Installing...
📌 Adjusting configuration...
🩹 Patching environment...
⏲ Done in 0:00:08
🔁 Restarting kernel...


In [ ]:
import condacolab
condacolab.check()

✨🍰✨ Everything looks OK!


In [ ]:
!python rapidsai-csp-utils/colab/install_rapids.py stable

import os
os.environ['NUMBAPRO_NVVM'] = '/usr/local/cuda/nvvm/lib64/libnvvm.so'
os.environ['NUMBAPRO_LIBDEVICE'] = '/usr/local/cuda/nvvm/libdevice/'
os.environ['CONDA_PREFIX'] = '/usr/local'

## Load data using cudf

In [ ]:
import cudf as pd


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab/ethnicolor/data/fl_reg_name_race_2022.csv.gz')

In [ ]:
df.head()

name_last name_first      race
0  Hessler-Smith      Jason  nh_white
1         Rogers      Renee  nh_white
2      Bartolome    Crystal  nh_white
3         Bailey      Donna  nh_white
4        Carlson   Greggory  nh_white

In [ ]:
df.describe()

/usr/local/lib/python3.10/site-packages/cudf/core/dataframe.py:4953: FutureWarning: `datetime_is_numeric` is deprecated. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  warnings.warn(
/usr/local/lib/python3.10/site-packages/cudf/core/series.py:3120: FutureWarning: `datetime_is_numeric` is deprecated and will be removed in a future release. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  warnings.warn(


name_last name_first      race
count   15455009   15455080  15455110
unique   1341197     641105         8
top        Smith    Michael  nh_white
freq       79362     153753   9446851

In [ ]:
df['race'].unique()

0            asian
1         hispanic
2     multi_racial
3    native_indian
4         nh_black
5         nh_white
6            other
7          unknown
Name: race, dtype: object

In [ ]:
df.dropna(subset=['name_first', 'name_last'], inplace=True)

In [ ]:
df.describe()

/usr/local/lib/python3.10/site-packages/cudf/core/dataframe.py:4953: FutureWarning: `datetime_is_numeric` is deprecated. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  warnings.warn(
/usr/local/lib/python3.10/site-packages/cudf/core/series.py:3120: FutureWarning: `datetime_is_numeric` is deprecated and will be removed in a future release. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  warnings.warn(


name_last name_first      race
count   15454979   15454979  15454979
unique   1341194     641100         8
top        Smith    Michael  nh_white
freq       79362     153753   9446764

In [ ]:
df.groupby('race').agg({'name_last': 'nunique'})

name_last
race                    
asian              81743
hispanic          442817
multi_racial       37859
native_indian      23064
nh_black          162943
nh_white          802901
other             105674
unknown           143439

In [ ]:
df['full_name'] = df['name_last'] + ' ' + df['name_first']

In [ ]:
df.head()

name_last name_first      race            full_name
0  Hessler-Smith      Jason  nh_white  Hessler-Smith Jason
1         Rogers      Renee  nh_white         Rogers Renee
2      Bartolome    Crystal  nh_white    Bartolome Crystal
3         Bailey      Donna  nh_white         Bailey Donna
4        Carlson   Greggory  nh_white     Carlson Greggory

## Get features using CountVectorizer

In [ ]:
from cuml.feature_extraction.text import CountVectorizer

In [ ]:
import cuml

In [ ]:
cuml.global_settings.output_type

In [ ]:
vectorizer = CountVectorizer(analyzer='char')

In [ ]:
X = vectorizer.fit_transform(df['full_name'])

In [ ]:
X[:10].toarray()

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 2., 0., 0., 2., 1., 1., 0., 1., 1., 1., 1., 0., 0.,
        1., 4., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 4., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
        3., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2.,
        1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 2., 1., 0., 2., 0., 0.,
        2., 1., 2., 0., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2.,
        1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 2., 1

In [ ]:
vectorizer.get_feature_names()

0      
1     "
2     #
3     %
4     '
5     (
6     )
7     *
8     +
9     ,
10    -
11    .
12    /
13    0
14    1
15    2
16    3
17    4
18    5
19    6
20    7
21    8
22    ;
23    =
24    ?
25    @
26    [
27    \
28    ]
29    _
30    `
31    a
32    b
33    c
34    d
35    e
36    f
37    g
38    h
39    i
40    j
41    k
42    l
43    m
44    n
45    o
46    p
47    q
48    r
49    s
50    t
51    u
52    v
53    w
54    x
55    y
56    z
57    ~
Name: token, dtype: object

In [ ]:
len(vectorizer.get_feature_names())

58

In [ ]:
vocab = vectorizer.get_feature_names()

In [ ]:
df.head()

name_last name_first      race            full_name  race_code
0  Hessler-Smith      Jason  nh_white  Hessler-Smith Jason          5
1         Rogers      Renee  nh_white         Rogers Renee          5
2      Bartolome    Crystal  nh_white    Bartolome Crystal          5
3         Bailey      Donna  nh_white         Bailey Donna          5
4        Carlson   Greggory  nh_white     Carlson Greggory          5

In [ ]:
X[0].toarray()

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 2., 0., 0., 2., 1., 1., 0., 1., 1., 1., 1., 0., 0.,
        1., 4., 1., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [ ]:
import cupy as np

np.unique(df.race.factorize()[0])

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int8)

In [ ]:
df['race_code'] = df.race.factorize()[0]

In [ ]:
df.head()

name_last name_first      race            full_name  race_code
0  Hessler-Smith      Jason  nh_white  Hessler-Smith Jason          5
1         Rogers      Renee  nh_white         Rogers Renee          5
2      Bartolome    Crystal  nh_white    Bartolome Crystal          5
3         Bailey      Donna  nh_white         Bailey Donna          5
4        Carlson   Greggory  nh_white     Carlson Greggory          5

In [ ]:
df[['race', 'race_code']].drop_duplicates().sort_values('race_code')

race  race_code
32           asian          0
22        hispanic          1
158   multi_racial          2
66   native_indian          3
5         nh_black          4
0         nh_white          5
6            other          6
120        unknown          7

In [ ]:
race_id_df = df[['race', 'race_code']].drop_duplicates().sort_values('race_code')

In [ ]:
race_id_df

race  race_code
32           asian          0
22        hispanic          1
158   multi_racial          2
66   native_indian          3
5         nh_black          4
0         nh_white          5
6            other          6
120        unknown          7

In [ ]:
race_to_id = {}
id_to_race = {}

for index, row in race_id_df.to_pandas().iterrows():
    race_to_id[row['race']] = row['race_code']
    id_to_race[row['race_code']] = row['race']

In [ ]:
race_to_id

{'asian': 0,
 'hispanic': 1,
 'multi_racial': 2,
 'native_indian': 3,
 'nh_black': 4,
 'nh_white': 5,
 'other': 6,
 'unknown': 7}

In [ ]:
id_to_race

{0: 'asian',
 1: 'hispanic',
 2: 'multi_racial',
 3: 'native_indian',
 4: 'nh_black',
 5: 'nh_white',
 6: 'other',
 7: 'unknown'}

In [ ]:
y = df.race_code.to_cupy()

In [ ]:
X = X.toarray()

In [ ]:
y[0]

array(5, dtype=int8)

In [ ]:
y.shape

(15454979,)

In [ ]:
type(X)

cupyx.scipy.sparse._csr.csr_matrix

## Preparing for training

In [ ]:
from cuml.model_selection import train_test_split

X_train,  X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
from cuml.ensemble import RandomForestClassifier

## Training

In [ ]:
#Create a Gaussian Classifier
clf = RandomForestClassifier(split_criterion='entropy', random_state=42, verbose=True)
#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train, y_train)

/usr/local/lib/python3.10/site-packages/cuml/internals/api_decorators.py:344: UserWarning: For reproducible results in Random Forest Classifier or for almost reproducible results in Random Forest Regressor, n_streams=1 is recommended. If n_streams is > 1, results may vary due to stream/thread timing differences, even when random_state is set
  return func(**kwargs)


RandomForestClassifier()

## Accuracy using test dataset

In [ ]:
y_pred = clf.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:", cuml.metrics.accuracy.accuracy_score(y_test, y_pred))

Accuracy: 0.6747448444366455


## Save model and vectorizer

In [ ]:
import joblib

joblib.dump(clf, "/content/drive/MyDrive/Colab/ethnicolor/fl_voter_name_2022_rf_model_1g.joblib", compress=3)  # compression is ON!
joblib.dump(vectorizer, "/content/drive/MyDrive/Colab/ethnicolor/fl_voter_name_2022_rf_vect_1g.joblib", compress=3)  # compression is ON!

['/content/drive/MyDrive/Colab/ethnicolor/fl_voter_name_2022_rf_vect_1g.joblib']